HelloSignW9API/Models/Winner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelloSignW9API.Models
{
    public class Winner
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [EmailAddress]
        [RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$", ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }       
        public string Date { get; set; }      

        [Required]
        public string Name { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string TaxClassification { get; set; }
        public string AccountNumber { get; set; }
        public string RequestersName { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string EmployerNumber { get; set; }
        public string Signature { get; set; }
        public byte[] FormW9 { get; set; }
        public string SignId { get; set; }
    }
}

HelloSignW9API/Controllers/WinnersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using HelloSign;
using HelloSignW9API.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HelloSignW9API.Controllers
{
    public class WinnersController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Winner Winner { get; set; }

        public WinnersController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
          
            return View();
        }

        //CREATE
        public IActionResult Create(int? id)
        {
            Winner = new Winner();
            if (id == null)
            {
                return View(Winner);
            }                    


            return View(Winner);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create()
        {
           
            if (ModelState.IsValid)
            {
                
                if(Winner.Id == 0)
                {
                    Winner.Date = Convert.ToString(DateTime.Now);


                    var client = new Client("c630c721fc54967c46d087051cb723df25eb3345d1fa53a1989b5614345bf6b5");
                    var request = new TemplateSignatureRequest();

                    request.AddTemplate("6ffae7883ad011c21ea8adced0c002f7df5ea428");
                    request.Subject = "Testing template.";
                    request.Message = "Testing template.";
                    request.AddCustomField("DateSigned", Winner.Date);
                    request.AddSigner("Client", Winner.Email, Winner.Name);
                    request.SigningOptions = new SigningOptions
                    {
                        Draw = true,
                        Type = true,
                        Upload = true,
                        Phone = false,
                        Default = "draw"
                    };
                    request.TestMode = true;
                    var response = client.SendSignatureRequest(request);
                    Winner.SignId = response.SignatureRequestId;
                    Console.WriteLine("New Template Signature Request ID: " + response.SignatureRequestId);

                    _db.Winners.Add(Winner);
                }
                _db.SaveChanges();                            

              
                return RedirectToAction("Index");
            }

            return View(Winner);
        }

        //UPDATE
        public IActionResult Update(int? id, string fileName)
        {
            Winner = new Winner();
            Winner = _db.Winners.FirstOrDefault(u => u.Id == id);           


            if (Winner == null)
            {
                return NotFound();
            }

            return View(Winner);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update()
        {            
            if (ModelState.IsValid)
            {
                if (Winner.Id == 0)
                {
                   
                } else
                {
                    string signatureId = Winner.SignId;
                    var client = new Client("c630c721fc54967c46d087051cb723df25eb3345d1fa53a1989b5614345bf6b5");
                    client.DownloadSignatureRequestFiles(signatureId, "C:/Users/Leslie Zaragosa/Downloads/output.pdf");

                    //STATUS

                    var request = client.GetSignatureRequest(signatureId);
                    var status = request.Signatures;

                    Console.WriteLine("Signature Request title: " + status);

                    _db.Winners.Update(Winner);
                }
                _db.SaveChanges();
              //  string path = Path.Combine(@"C:\Users\Leslie Zaragosa\Downloads", "output.pdf");
              //  return File(path, "application/pdf");
              //  return RedirectToAction("Index");
            }

            return View(Winner);
        }

        #region

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Winners.ToListAsync() });
        }

        #endregion
    }
}

HelloSignW9API/Views/Winners/Create.cshtml
@model HelloSignW9API.Models.Winner

<br />

<div class="border container" style="padding: 30px;">
    <form method="post" asp-action="Create">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
        }

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Name">Full name:</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger mb-2"></span>
            <br />
            <label asp-for="Email">Email:</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger mb-2"></span>
           

            <div class=" form-group row">

                <div class="col mt-2">
                    <button type="submit" class="btn btn-primary form-control">Add new record</button>
                </div>
                <div class="col mt-2">
                    <a asp-action="Index" class="btn btn-success form-control">Back to list</a>
                </div>

            </div>


        </div>
    </form>
</div>

@section Scripts{ 
<partial name="_ValidationScriptsPartial" />
}

HelloSignW9API/Views/Winners/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #afe8f1;">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Karrot</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse ">
                <ul class="navbar-nav ml-auto">                    
                    <li class="nav-item">
                        <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Privacy">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<br />

<div class=" container row p-0 m-0">

    <div class="col-4 mb-5 mr-0 ml-0" >
        <a asp-action="Create" asp-controller="Winners" class="btn btn-info form-control text-white">
            Add new record
        </a>
    </div>
    <br />

    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width: 100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                   
                    <th></th>
                </tr>
            </thead>
        </table> 

    </div>

</div>

@section Scripts{ 
<script src="~/js/winnerList.js"></script>
}

HelloSignW9API/Views/Winners/Update.cshtml
@model HelloSignW9API.Models.Winner

@{
    ViewData["Title"] = "Update";
}

<div class="border container mt-5" style="padding: 30px;">
    <form method="post" asp-action="Update">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="SignId" />
            <input type="hidden" asp-for="Adress" />
            <input type="hidden" asp-for="City" />
            <input type="hidden" asp-for="Date" />
        }

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">


            <div class="form-group row">

                <div class="col-3">
                    <label asp-for="Email">Email:</label>
                </div>
                <div class="col-6">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger mb-2"></span>
                </div>

            </div>

            <div class="form-group row">

                <div class="col-3">
                    <label asp-for="Name">Name:</label>
                </div>
                <div class="col-6">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger mb-2"></span>
                </div>

            </div>

            <div class="form-group row">

                <div class="col-3">
                    <label asp-for="Adress">Adress:</label>
                </div>
                <div class="col-6">
                    <input asp-for="Adress" class="form-control" disabled />
                    <span asp-validation-for="Adress" class="text-danger mb-2"></span>
                </div>

            </div>

            <div class="form-group row">

                <div class="col-3">
                    <label asp-for="City">City:</label>
                </div>
                <div class="col-6">
                    <input asp-for="City" class="form-control" disabled />
                    <span asp-validation-for="City" class="text-danger mb-2"></span>
                </div>

            </div>

            <div class="form-group row">

                <div class="col-3">
                    <label asp-for="Date">Date:</label>
                </div>
                <div class="col-6">
                    <input asp-for="Date" class="form-control" disabled />
                    <span asp-validation-for="Date" class="text-danger mb-2"></span>
                </div>

            </div>


            <div class=" form-group row">

                <div class=" mt-2 mr-2">
                    <a asp-action="Index" class="btn  btn-outline-info  form-control">Back to list</a>
                </div>

                <div class=" mt-2">
                    <button type="submit" class="btn btn-info float-right form-control">Download W9 Form</button>
                </div>


            </div>


        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}